name: Builder

on: ["push", "pull_request", "workflow_dispatch"]

permissions:
  contents: write

jobs:
  build:
    name: Build Decky TDP Control
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up NodeJS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
  
    - name: Install JS dependencies
      run: |
        npm i -g pnpm
        pnpm i --frozen-lockfile
      
    - name: Build Frontend
      run: |
        pnpm run build
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        path: "./decky-tdp-control"
        filename: 'decky-tdp-control.zip'
        exclusions: '*.git* /*node_modules/* /*assets/* /*vscode/* /*src/* package-lock.json .prettierrc pnpm-lock.yaml README.md rollup.config.js tsconfig.json'
      
    - name: Upload package artifact
      uses: ncipollo/release-action@v1
      with:
        artifacts: "decky-tdp-control.zip"